require('plugins')
require('remaps')
require('plugins')
require('sets')
require('colorscheme')

require('plugins.gitsigns')
require('plugins.smoothie')
require('plugins.lspsaga')
require('plugins.compe')
require('plugins.galaxyline')

require('lsp.init')
require('lsp.bash')
require('lsp.css')
require('lsp.docker')
require('lsp.graphql')
require('lsp.html')
require('lsp.json')
require('lsp.lua')
require('lsp.ts')
require('lsp.vim')
require('lsp.yaml')

