return {
    ["BASH"] = "bashls",
    ["CSS"] = "cssls",
    ["DOCKER"] = "dockerls",
    ["GRAPHQL"] = "graphql",
    ["HTML"] = "html",
    ["JSON"] = "jsonls",
    ["LUA"] = "sumneko_lua",
    ["TYPESCRIPT"] = "tsserver",
    ["VIM"] = "vimls",
    ["YAML"] = "yamlls",
    ["PRISMA"] = "prismals",
    ["XML"] = "lemminx",
    ["TOML"] = "taplo",
}
